# coding=utf-8

REDIS_CONN_URI = "redis://:Dcappredi3@10.22.81.61:6379"
REDIS_HOST = "10.22.81.61"
REDIS_PASS = "Dcappredi3"

BROKER_URL_INFO_DB = "/1"
CELERY_RESULT_BACKEND_INFO_DB = "/2"


BROKER_URL = REDIS_CONN_URI + BROKER_URL_INFO_DB
CELERY_RESULT_BACKEND = REDIS_CONN_URI + CELERY_RESULT_BACKEND_INFO_DB

CELERY_TASK_SERIALIZER = 'msgpack'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
CELERY_ACCEPT_CONTENT = ['json', 'msgpack']
CELERYD_MAX_TASKS_PER_CHILD = 40
CELERY_IGNORE_RESULT = True
CELERY_TIMEZONE = 'Asia/Shanghai'


